server:
  port: 8080
spring:
  application:
    name: user-proxy

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 5
      metadataMap:
        instanceId: "${spring.application.name}:${random.value}"